# aws에 로그인하지 않고 현재 배포된 인스턴스를 지우는 편의 워크플로우
name: clear blue

on:
  workflow_dispatch:

jobs:
  clear-blue:
    if: github.repository == 'BaGulBaGul/BaGulBaGul_Front'
    runs-on: ubuntu-latest
    env:
      ENV_KEY: env
      ENV_BLUE_NAME: bagulbagul-frontend-main-blue
    steps:
      - name: asg-blue를 찾아서 인스턴스 수를 0으로 변경
        run: |          
          # asg blue를 찾는다
          ASG_BLUE_NAME=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?Tags[?Key=='$ENV_KEY' && Value=='$ENV_BLUE_NAME']].AutoScalingGroupName" --output text)
          # asg-blue가 존재하는지 확인
          if [ -z "$ASG_BLUE_NAME" ]; then
            echo "Error: asg-blue를 찾을 수 없습니다."
            exit 1
          fi
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_BLUE_NAME --desired-capacity 0